#!/bin/sh

# change the following informations according to your needs.

HOST=$1
BASEDIR=$2
NUM=$3
LIBPATH=./lib
if [ x"$LIBPATH" != x ]; then
  if [ x"$LD_LIBRARY_PATH" = x ]; then
    LD_LIBRARY_PATH=$LIBPATH
  else
    LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH
  fi
  export LD_LIBRARY_PATH
fi

# Put here the name of your team
teamname="CESAR_School"

DIR=`dirname $0`

player="${DIR}/src/CESAR_School_player"
coach="${DIR}/src/CESAR_School_coach"
#player="./src/CESAR_School_player"
#coach="./src/CESAR_School_coach"

config="./src/player.conf"
config_dir="./src/formations-dt"
coach_config="./src/coach.conf"

opt="--player-config ${config} --config_dir ${config_dir}"
opt="${opt} -h ${HOST} -t ${teamname}"

coachopt="--coach-config ${coach_config}"
coachopt="${coachopt} -h ${HOST} -t ${teamname}"

team_graphic="--use_team_graphic on --team_graphic_file ./src/team_logo.xpm"
coachopt="${coachopt} ${team_graphic}"

cd $BASEDIR

case $NUM in
    1)
        $player $opt -g
        ;;
    2)
        $coach $coachopt
        ;;
    *)
        $player $opt
        ;;
esac
